/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { generateEyeMaterial } from 'utils';
import { ApiFaceInfoEntityResponse } from 'generated';

type GLTFResult = GLTF & {
    nodes: {
        EyeLeft: THREE.Mesh;
        EyeRight: THREE.Mesh;
        Wolf3D_Head: THREE.Mesh;
        Wolf3D_Teeth: THREE.Mesh;
        Wolf3D_Body: THREE.Mesh;
        Wolf3D_Hair: THREE.Mesh;
    };
    materials: {
        Wolf3D_Eye: THREE.MeshStandardMaterial;
        Wolf3D_Skin: THREE.MeshStandardMaterial;
        Wolf3D_Teeth: THREE.MeshStandardMaterial;
        Wolf3D_Body: THREE.MeshStandardMaterial;
        Wolf3D_Hair: THREE.MeshStandardMaterial;
    };
};

export default function ManModelBase({
    faceInfo,
    ...props
}: JSX.IntrinsicElements['group'] & { faceInfo: ApiFaceInfoEntityResponse }) {
    const group = useRef<THREE.Group>();
    const { nodes, materials } = useGLTF('/common-man/man-model.gltf') as GLTFResult;
    const leftEyeMaterial = generateEyeMaterial(faceInfo.leftEyeColor);
    const rightEyeMaterial = generateEyeMaterial(faceInfo.rightEyeColor);

    return (
        <group ref={group} {...props} dispose={null} position={[0, -1.6, 0]}>
            <mesh geometry={nodes.EyeLeft.geometry} material={leftEyeMaterial} />
            <mesh geometry={nodes.EyeRight.geometry} material={rightEyeMaterial} />
            <mesh
                geometry={nodes.Wolf3D_Head.geometry}
                material={materials.Wolf3D_Skin}
                material-color={faceInfo.skinColor}
            />
            <mesh geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} />
            <mesh
                geometry={nodes.Wolf3D_Hair.geometry}
                material={materials.Wolf3D_Hair}
                material-color={faceInfo.hairColor}
            />
        </group>
    );
}

useGLTF.preload('/common-man/man-model.gltf');
